name: Reusable - Build, Scan & Push Image

on:
  workflow_call:
    inputs:
      service_name:
        description: "Name of the service"
        required: true
        type: string
      environment:
        description: "Target environment: dev"
        required: true
        type: string
      branch:
        description: "Branch that triggered the build"
        required: true
        type: string
      sha:
        description: "Git SHA of the commit"
        required: true
        type: string

    outputs:
      image_tag:
        description: "The Docker image tag that was built"
        value: ${{ jobs.build.outputs.image_tag }}

    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    name: Build, Scan & Push - ${{ inputs.service_name }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: meta
        run: |
          SHORT_SHA=$(echo ${{ inputs.sha }} | cut -c1-7)
          TAG="dev-${SHORT_SHA}"
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
          echo "Image tag: ${TAG}"

      - name: Debug secrets (boolean)
        run: |
          echo "USERNAME: ${{ secrets.DOCKERHUB_USERNAME != '' }}"
          echo "TOKEN: ${{ secrets.DOCKERHUB_TOKEN != '' }}"
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.service_name }}:${{ steps.meta.outputs.tag }}

      - name: Trivy image scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.service_name }}:${{ steps.meta.outputs.tag }}
          format: table
          exit-code: '1'
          severity: CRITICAL

      - name: Push image to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.service_name }}:${{ steps.meta.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.service_name }}:dev-latest
